DROP TABLE IF EXISTS users CASCADE;
DROP TABLE IF EXISTS ladders CASCADE;
DROP TABLE IF EXISTS accounts CASCADE;
DROP TABLE IF EXISTS characters CASCADE;
DROP TABLE IF EXISTS accounts CASCADE;
DROP TABLE IF EXISTS items CASCADE;
DROP TABLE IF EXISTS favourites CASCADE;

CREATE TABLE users(
  id SERIAL PRIMARY KEY NOT NULL, 
  name VARCHAR(255) NOT NULL, 
  email VARCHAR(255) NOT NULL, 
  password VARCHAR(255) NOT NULL
);

CREATE TABLE ladders(
  id SERIAL PRIMARY KEY NOT NULL,
  name VARCHAR(255),
  last_requested TIMESTAMPTZ,
  rankings JSON
);

CREATE TABLE accounts(
  id SERIAL PRIMARY KEY NOT NULL, 
  name VARCHAR(255) NOT NULL,
  twitch VARCHAR(255)
);

CREATE TABLE characters(
  id SERIAL PRIMARY KEY NOT NULL,
  account_name VARCHAR(255),
  account_twitch VARCHAR(255),
  account_id INTEGER REFERENCES accounts(id) ON DELETE CASCADE,
  ladder_id INTEGER REFERENCES ladders(id) ON DELETE CASCADE,
  name VARCHAR(255),
  level INTEGER,
  class VARCHAR(255),
  experience BIGINT,
  last_requested TIMESTAMP
);

CREATE TABLE items(
  id SERIAL PRIMARY KEY NOT NULL, 
  character_id INTEGER REFERENCES characters(id) ON DELETE CASCADE,
  items JSON
);

CREATE TABLE favourites(
  id SERIAL PRIMARY KEY NOT NULL, 
  user_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
  character_name VARCHAR(255) NOT NULL
);